api:
    client_secret: "https://developers.strava.com/docs/getting-started/"
    refresh_token: "https://developers.strava.com/docs/getting-started/"
    
athlete:
    id: 123

commutes:
    house_one_to_work_location_one:
        - "SW1A1AA"
        - "SW1A1AA"
    house_one_to_work_location_two:
        - "SW1A1AA"
        - "SW1A1AA"
    house_two_to_work_location_two:
        - "SW1A1AA"
        - "SW1A1AA"
    house_two_to_work_location_three:
        - "SW1A1AA"
        - "SW1A1AA"
